### ISSUE TITLE
Skill not validating signatures on incoming requests

### ISSUE THREAD

**Issue by olipachi** [AreYouFreeBusy/AlexaSkillsKit.NET#35] opened 2017-07-06 17:18 UTC
We recently submitted our skill to Amazon for certification and they came back with:

"The skill end-point is not validating the signatures for incoming requests and is accepting requests with an incorrect certificate URL. Please make sure that your signature validation is correct. To reject an invalid request with an invalid signature or certificate, the skill should respond with HTTP status code 400 (Bad Request) in the response."

Any guidance on how to resolve this issue?

Thanks.

**Comment by stefann42** [comment] 2017-07-06 17:38
The best way would be to ask the certification team which signature validation test in their suite is failing which would tells us if updates need to be made to the library or if the problem is with your skill. However, historically, the certification team has not been helpful as to hold such a dialogue.

In absence of that information, gather all the HTTP request/response logs that were generated during the certification test (look for requests to which your skill responded with HTTP Status Code 400) and try to understand what request payloads they sent to your skill. You can then compare with the requirements published at https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/developing-an-alexa-skill-as-a-web-service and we can compare with the reference implementation in their Java library https://github.com/amzn/alexa-skills-kit-java/tree/master/src/com/amazon/speech/speechlet/verifier

**Comment by olipachi** [comment] 2017-07-06 18:13
Okay, will try this. Can you clarify where in the Speechlet flow the cert validation occurs? Where can I override the validation?

**Comment by stefann42** [comment] 2017-07-06 18:44
See https://github.com/AreYouFreeBusy/AlexaSkillsKit.NET/blob/master/README.md#override-request-validation-policy

**Comment by stefann42** [comment] 2018-01-18 13:03
@olipachi Closing this issue because we don't have other reports of failing to validate signatures with release v1.5.2 and later.

**Closed by stefann42** 2018-01-18 13:03 UTC
